### ISSUE TITLE
No entities show

### ISSUE THREAD

**Issue by hugosbnarciso** [slinkymanbyday/badnest#7]
Hi,

No entities show. In the log there's no errors for this component and it seems it picks up the token correctly.

Any idea?

Thanks,
H

**Comment by slinkymanbyday** [comment]
What is your config and what devices do you have?

**Comment by hugosbnarciso** [comment]
Hello,

I have a Google Nest Thermostat.

```
badnest:
  issue_token: !secret badnest_issuetoken
  cookie: !secret badnest_cookie
  region: ae

climate:
  - platform: badnest
    scan_interval: 10
    
sensor:
  - platform: badnest
```
